name: Build and deploy Node.js project to Azure Function App - newlinker-fn

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read    # for checkout & artifacts
  actions: write    # to delete workflow runs

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '22.x'

jobs:
  # … your existing build & deploy jobs … #

  cleanup:
    name: Delete previous workflow runs
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ always() }}
    permissions:
      actions: write

    steps:
      - name: “Delete all runs except this one”
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          CURRENT_RUN: ${{ github.run_id }}
        run: |
          echo "Fetching workflow runs for $REPO..."
          # Grab up to 100 of the most recent runs of this workflow
          runs=$(curl -sSf \
                   -H "Authorization: Bearer $GITHUB_TOKEN" \
                   -H "Accept: application/vnd.github.v3+json" \
                   "https://api.github.com/repos/$REPO/actions/runs?workflow_id=${{ github.workflow }}&per_page=100" \
                 | jq -r '.workflow_runs[] | .id')

          for run_id in $runs; do
            if [[ "$run_id" != "$CURRENT_RUN" ]]; then
              echo "Deleting run $run_id …"
              curl -sSf -X DELETE \
                   -H "Authorization: Bearer $GITHUB_TOKEN" \
                   "https://api.github.com/repos/$REPO/actions/runs/$run_id"
            fi
          done
          echo "Cleanup complete."
